### ISSUE TITLE
Erro de percepção 

### ISSUE THREAD

**Issue by guilhermediasl** [iWarhead/wumpusgrp3#10]
External run_agent([no,no,no,no,no],goforward)
--------------------------------
|           |           |           |           |
---------------------------------
|     P  | W     |           |    P   |
---------------------------------
|           |      G |           |    P   |
---------------------------------
|           |           |   A    |           |
---------------------------------
wumpus_health(alive)
agent_location(3,1)
agent_orientation(0)
agent_health(alive)
agent_arrows(1)
agent_gold(0)
percebi: _L200[no,no,no,no,no]

External run_agent([no,no,no,no,no],goforward)
--------------------------------
|         |         |         |         |
--------------------------------
|     P  | W     |         |     P  |
--------------------------------
|         |      G |         |     P  |
---------------------------------
|         |         |         |   A    |
---------------------------------
wumpus_health(alive)
agent_location(4,1)
agent_orientation(0)
agent_health(alive)
agent_arrows(1)
agent_gold(0)
percebi: _L200[no,yes,no,no,no]
External function run_agent(Percept,Action) failed miserably!
false.

Não consegui entender o motivo da percepção no ultimo caso não ter retornado yes na trombada ([_,_,_,yes,_])

**Comment by drbeco** [comment]
Ficou difícil de ler. Tente usar os três acentos graves, que é o comando para código com fonte monoespaçada. Veja a formatação aqui: https://guides.github.com/features/mastering-markdown/

**Comment by drbeco** [comment]
Outra coisa, ele só tromba se tentar passar para **além** da parede. Só de chegar na última casa não dá trombada, não.

**Comment by guilhermediasl** [comment]
Entendido professor , obrigado.
