### ISSUE TITLE
Posição dos buracos.

### ISSUE THREAD

**Issue by eilins** [iWarhead/wumpusgrp3#11]
Galera, o negocio é o seguinte. Foi determinado a quantidade de buracos para o mundo, só que nesse caso vamos criar uma lista para que a posição desses 3 buracos variem dentro do mundo, ou vamos determinar uma zona dita "segura" fixando a posição dos buracos?

**Comment by flavioduart** [comment]
Não, a posição dos buracos é aleatória, de acordo com o mundo do wumpus. Temos que fazer listas de casas seguras, visitadas, etc, para fazer que ele contorne buracos e coisas do tipo.

**Comment by drbeco** [comment]
Tem que pensar "como" o agente. Que listas você precisa para deduzir tudo? Por exemplo, uma lista de casas em que é "possível" ter buracos? Apenas uma ideia...
