### ISSUE TITLE
Erro nas funções 

### ISSUE THREAD

**Issue by eilins** [iWarhead/wumpusgrp3#12]
Pessoal, como o professor atualizou o mundo do wumpus, as funções antigas como agent_gold e agent_location estão dando como falhas e impossibilitando a realização da movimentação. Alguém saberia como resolver?

**Comment by flavioduart** [comment]
Sim, Vinícius. De momento, apenas retirei as funções, pois elas estavam impossibilitando a inteligencia do agente. Então Bug resolvido.

**Comment by flavioduart** [comment]
Mas iremos pensar em como/quais funções colocar no lugar das que foram retiradas!
