### ISSUE TITLE
adjacentes(Posicao, Lista) 

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#14]
Oi pessoal, queria dar uma sugestão importante.

Poderíamos ter uma função que retornasse as casas adjacentes a casa atual (ou a qualquer casa dada).

Por exemplo, se estou na casa `minhaposicao([2,2])` e chamo:

```
minhaposicao(P),
adjacentes(P, L)
```

Então `L=[[3,2], [2,3], [1,2], [2,1]]`

Ou se estou na posição `[1,1]`, então a lista fica apenas com `L=[[2,1], [1,2]]`

Essa função é uma intermediária para depois ser usada em funções mais complexas.

**Comment by iWarhead** [comment]
Obrigado pela sugestão professor, estamos pensando em maneiras de usar listas para facilitar e otimizar o trabalho.

**Comment by drbeco** [comment]
Vocês estão tratando listas como bichos de sete cabeças. Falou a palavra lista, já assusta.

Esse caso aqui é muito simples. Listas só precisam de mais conhecimento se forem usar `[Head|Tail]`. Aqui nesta função nem precisa!

Eu poderia ter falado para ser:

`adjacentes(Posicao, Leste, Norte, Oeste, Sul)`

E daria o mesmo resultado. Mas aí fica ruim, pois se por exemplo `Oeste` e `Sul` for impossível (como é o caso de estar na casa `[1,1]`), teria que retornar algo para marcar que não é válido. Enquanto que se retornar apenas uma lista, dá para ignorar as que não existem e colocar na lista apenas as casas possíveis.

Então a pergunta é: como implementar?! Coloquem a mão na massa. Discutam e façam.

**Comment by drbeco** [comment]
Sem discussão? Foi implementado?

**Comment by drbeco** [comment]
Questão:

Se eu tenho uma lista de casas seguras, uma lista de casa adjacentes e uma lista de casas visitadas, e quero calcular uma lista opções de casas para visitar em seguida, quais operações de conjuntos eu faço? (União, intersecção, subtração, etc.)?

Suponha:

```
CS = lista de casas seguras
CV = lista de casas visitadas
CA = lista de casas adjacentes
CO = lista de opções de casas para visitar nas próximas rodadas
```

Então a fórmula lógica é?

`CO = ??`

---

Operações `PROLOG` para testar:

```
$ swipl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 6.6.6)
Copyright (c) 1990-2013 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- union([[1,1], [2,2]], [[1,1], [3,3]], L).
L = ??

?- list_to_set([[1,1], [2,2], [1,1], [3,3]], L).
L = ??

?- intersection([[1,1], [2,2], [3,3], [2,1]], [[1,1], [2,2], [1,2]], L).
L = ??

?- subtract([[1,1], [2,2], [3,3], [4,4], [2,1]], [[4,4],[2,1],[1,2]], L).
L = ??

?- 
```

Discussão abaixo:

**Comment by flavioduart** [comment]
Professor, acredito que fazendo:

**bold CO= CS + (CA ^ CV)** 

daria certo.

**Comment by drbeco** [comment]
Coloque sua ideia em teste. Use listas fictícias iguais as que coloquei acima no prompt do PROLOG. Não é necessário código fonte. Digite direto no interpretador. Veja se corrobora sua tese.

**Comment by drbeco** [comment]
Exemplo:

```
-----------------------------------------
|         |     P   |         |       G |
-----------------------------------------
|         |     P   | W       |         |
-----------------------------------------
|         |         |     P   |         |
-----------------------------------------
|         |   A     |         |         |
-----------------------------------------
```

Suponha que o agente já andou por `[1,1]`, `[2,1]` e `[3,1]` e está de volta para a casa `[2,1]` e agora quer calcular uma casa segura e não visitada e adjacente (no caso a resposta é a casa `[2,2]`). Como fazer?

Faça as listas:

```
CS = lista de casas seguras
CV = lista de casas visitadas
CA = lista de casas adjacentes
```

Faça um teste no prompt do PROLOG com a fórmula por você criada:
```
CO = fórmula? Lista resultante?
```

Mostre a fórmula usando as operações acima (intersecção, união, subtração, ou outra operação de lista/conjunto que precisar), mostre o teste feito no `swipl` (direto no prompt).

**Comment by guilhermediasl** [comment]
intersection(CS,CA,Formula1),
subtract(Formula1,CV,Formula2).

CO = Formula2
