### ISSUE TITLE
Assert e retractall.

### ISSUE THREAD

**Issue by guilhermediasl** [iWarhead/wumpusgrp3#17]
Não entendo o porquê de sempre dar o seguinte erro ao usar assert ou retractall no agente :      
ERROR: assert/1: No permission to modify static procedure `minhacasa/2'

**Comment by drbeco** [comment]
Qual a linha do código fonte? Precisa descrever melhor o bug, senão não dá para outras pessoas te ajudar. Fui olhar o código do develop e não tem nada de "minhacasa" lá.

**Comment by guilhermediasl** [comment]
Por não estar funcionando eu apaguei , mas uma outra regra que da o mesmo erro é : 
encrenca([yes,_,_,_,_],shoot):-
retractall(encrenca([yes,_,_,_,_],shoot)).

**Comment by guilhermediasl** [comment]
Li a respeito e vi que precisaria usar algo como
:- dynamic
          encrenca/2.
Correto? botei logo após os writes do agente e não funcionou .

**Comment by drbeco** [comment]
Novamente você errou na formatação, e fica difícil de ler.

Suas listas estão com um monte de vírgulas seguidas `[yes,,,,,]` quando devia ser `[yes, _, _, _, _, _]`

Leia a explicação de formatação **Markdown** que passei no outro bug. O link fica bem acima da janela de edição **Styling with Markdown is supported**.

---

O uso do `retractall` tem que ser com variável anônima, pois ele "retract" "all" ou "apaga" "tudo".

Então se eu tenho na base `fato(1)` e `fato(2)` tenho que fazer `retractall(fato(_))` para apagar tudo.

**Comment by guilhermediasl** [comment]
Consegui implementar assert e retract no nosso agente , e agora também compreendo melhor a formatação e vou tentar evitar erros nesse sentindo , obrigado novamente professor.
