### ISSUE TITLE
Bug na saída do agente.

### ISSUE THREAD

**Issue by iWarhead** [iWarhead/wumpusgrp3#18]
Ao executar o agente o seguinte erro acontece ao final:

External function run_agent(Percept, Action) failed miserably!
false.

o que está causando isso?

**Comment by drbeco** [comment]
Isso ocorre quando sua função run_agent falha (retorna false).

Ela não pode falhar. Tem que retornar sempre true.

**Comment by drbeco** [comment]
Já descobriu qual a "percepção" que não está sendo considerada?

**Comment by iWarhead** [comment]
Bom, ao mostrar o erro ele mostra tambem que tipo de percepção causa isso, e uma delas é um [yes,yes,no,no,no], porém não temos isso no nosso agente, estaria o erro sendo causado pela falta de instrução para essa percepção?

**Comment by guilhermediasl** [comment]
Atualmente nosso agente não tem nenhuma resposta ao sentir brisa, então ele retorna falso e da o erro.

**Comment by guilhermediasl** [comment]
A mensagem de erro não existe mais.
