### ISSUE TITLE
Failed miserably

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#19]
Atualização (master/develop)
---

A mensagem 
`External function run_agent(Percept, No Action) failed miserably!`
agora mostra qual foi a percepção que o agente recebeu que não soube retornar uma ação.

**Comment by flavioduart** [comment]
Vai ajudar bastante na detecção de onde está o erro, professor.

**Comment by drbeco** [comment]
Fiz pensando exatamente nisso, para ajudar no debug.

**Comment by flavioduart** [comment]
Fecharei essa issue levando em consideração que todos os membros do grupo leram.
