### ISSUE TITLE
Onde iniciar dynamic

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#20]
O indicador `:-`
é usado pelo prolog para inicializar módulos, classes dinânicas, fazer "include" de bibliotecas, tec.

A linha

      :- dynamic([encrenca/2,flechas/1,direcao/1]).

Deve estar no início do código, abaixo apenas da linha `:- load_files([wumpus3]).`

**Comment by guilhermediasl** [comment]
Correção feita no feature, assim que terminarmos as outras correções enviaremos para o develop, obrigado professor.

**Comment by eilins** [comment]
Pronto professor, corrigido!
