### ISSUE TITLE
Fato dinâmico como fato estático

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#21]
A linha `17` :

    direcao(0).%Para saber a direca.

Declara `direcao(0).` como um fato estático, mas este fato é dinâmico. Então essa linha não deve existir, e sim um par retractall/assert no `init_agent`

**Comment by drbeco** [comment]
:question:

**Comment by flavioduart** [comment]
Professor, vi essa issue, mas ainda não consegui pegar bem o conceito de estático e dinâmio. Nesse momento estou dando uma pesquisada sobre, e tenho a intenção de resolver esse bug hoje, peço desculpas pelo tempo.

**Comment by flavioduart** [comment]
O senhor recomenda algum site, blog, ou material de estudo sobre? independente do idioma, não consigo achar nada muito explicativo. Me ajudaria bastante, e consequentemente ajudaria o grupo, obrigado.

**Comment by drbeco** [comment]
Fato estático é você escrever no código:

`direcao(0).`

Isso é um fato. Por estar escrito no código (linha 57) deve ser entendido como verdade absoluta sempre. Mas não é o caso: direcao(0) não é sempre verdade. Portanto deveria ser um fato dinâmico. Então em vez de escrever diretamente no código assim, tem que escrever `assert(direcao(0))`.

Ok?

Isso é para **fatos**. Outro ponto é para **regras**. O que diferencia um fato de uma regra é o `:-`. Um fato não pode ser cabeça de regra.

Aí vi outro erro importante: **existe** uma regra chamada `direcao(Direcao) :-` ( linhas 62 e 66)

Não pode criar **regra dinamica**. Ou `direcao` é um **fato** (que acho que deve ser o caso) ou é uma **regra**. 

Já pensou você apaga a regra de direção da memória com retract? Não vai funcionar!

Use outro nome para a regra e deixe direcao como fato apenas.

**Comment by flavioduart** [comment]
Entendi professor, resolverei com o grupo e resolveremos isso. Muito obrigado!!

**Comment by flavioduart** [comment]
Mudança feita.

**Comment by flavioduart** [comment]
Professor, depois que mudei, estava dando o erro "Trial 1". Creio que foi erro meu, mas gostaria de pedir ajuda ao senhor, ou a alguém do grupo que souber, para me mostrar onde eu errei e consertar.

**Comment by drbeco** [comment]
Eu expliquei em sala onde se deve colocar os `retractall` e `assert`. E não é jogado no meio do código como você fez. `assert` não é um **fato** do seu código para ficar no nível zero de indentação, sem nenhuma regra que o chame.

**Comment by drbeco** [comment]
Aliás, relendo o meu **primeiro post** deste mesmo bug, lá na descrição, eu já falei onde colocar o `assert`. Vamos prestar atenção!

**Comment by flavioduart** [comment]
Desculpa professor, entendi errado, tentarei dar um jeito.

**Comment by flavioduart** [comment]
Mudança feita!
