### ISSUE TITLE
Não use retract. Use retractall.

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#22]
Outro problema que falei em sala: **não use retract**, use **retractall**.

Já comentei isso, e o motivo é que fica muito difícil programar tentando cercar _fail_ vindo de `retract`. Já o `retractall` nunca falha, sempre funciona.

**Comment by flavioduart** [comment]
Entendido, ajeitarei e mudarei todos para retractall ainda hoje. Infelizmente não pude comparecer a sua ultima aula, mas já estou correndo atras e tentando aprender sobre, obrigado pela ajuda professor.

**Comment by flavioduart** [comment]
Pronto, todos retracts alterados.

**Comment by drbeco** [comment]
Se não fizer push no develop nenhum outro colaborador vai conseguir ver (inclusive eu!).

E pior, se adiar demais pushs no develop, vai dar conflito com alterações de outras pessoas.

**Comment by flavioduart** [comment]
Mas eu mandei pro develop, professor.

**Comment by drbeco** [comment]
:ok_hand:
