### ISSUE TITLE
Inicialização da montagem da Wiki e do projeto em PDF

### ISSUE THREAD

**Issue by eilins** [iWarhead/wumpusgrp3#23]
Galera, como já estamos a 2 semanas do prazo de finalização do projeto, começarei a montar nossa wiki e nosso projeto final em PDF, deixarei partes em relação ao funcionamento do programa para ir adicionando no decorrer que fomos resolvendo, e estou pensando em criar uma área de problemas recorrentes na formatação do Wumpus, que é justamente essas duvidas e esse problemas que estamos debatendo nos issues, para que caso o projeto fique disponível online, seja não só uma descrição do mundo Wumpus, mas seja um guia para possíveis usuários que se interessem por tentar programar. O que vocês acham? Continuem criando novos issues para servir de base para montagem. Valeu.

**Comment by iWarhead** [comment]
Apoio a idéia do guia.

**Comment by flavioduart** [comment]
Arthur, isso não se refere a Versão 0.4...

**Comment by flavioduart** [comment]
Se puder tirar (não sei se tem como), seria melhor

**Comment by iWarhead** [comment]
My bad.

**Comment by drbeco** [comment]
Todo issue deve ter um milestone associado. Se não é a versão 0.4, então que seja outra.

**Comment by flavioduart** [comment]
Isso, creio que a wiki ficaria melhor como a Versão 1.0, pois como não altera no programa, fica pra entrega final do trabalho.

**Comment by iWarhead** [comment]
Mas ele está falando dessa issue.

**Comment by flavioduart** [comment]
Issue "Inicialização da montagem da Wiki e do projeto em PDF", Versão 1.0 :smile_cat:

**Comment by drbeco** [comment]
Ué, eu estou falando das duas coisas! O issue do wiki e o próprio wiki! Não tem a mesma data? Ou vocês pretendem falar na issue que vão fazer wiki numa data e a issue em outra data? Parem de complicar, isso nem faz sentido.

**Comment by flavioduart** [comment]
Pessoal, dei inicio a wiki. Com o andar do código e entender do programa, faremos novas páginas. Fiquem a vontade para edita-la e criar páginas novas!

**Comment by flavioduart** [comment]
:watch:

**Comment by eilins** [comment]
PDF e wiki prontos!
