### ISSUE TITLE
Não confunda fato dinâmico com regra

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#24]
Sobre o comentário que fiz no bug #21 : 

---

Aí vi outro erro importante: **existe** uma regra chamada `direcao(Direcao) :-` ( linhas 62 e 66)

Não pode criar **regra dinamica**. Ou `direcao` é um **fato** (que acho que deve ser o caso) ou é uma **regra**. 

Já pensou você apaga a regra de direção da memória com retract? Não vai funcionar!

Use outro nome para a regra e deixe direcao como fato apenas.

---

É importante o suficiente para ter esse bug aberto só para ele.

Essa é uma falha de conceito importante demais! De volta ao estudo de PROLOG!

**Comment by iWarhead** [comment]
Talvez isto que esteja causando o erro atual, estou tentando consertar para poder dar o push no master, que está pelo menos 2 horas atrasado.

**Comment by iWarhead** [comment]
Bom, agora o erro de arguments are not sufficiently instantiated não está aparecendo, apenas o failed miserably.
