### ISSUE TITLE
Erro na função frente

### ISSUE THREAD

**Issue by guilhermediasl** [iWarhead/wumpusgrp3#26]
Nossa função de casa em frente , dada pelo professor em casa , não esta funcionando , a casa em frente fica [2,1]  em qualquer casa que o agente está, alguma sugestão?

Segue o código:

frente:-
      casaatual([X,Y]),
      direcao(Direcao),
      Direcao = 0,
      X1 is X + 1,
      retractall(casafrente(_)),
     assert(casafrente([X1,Y])).

**Comment by iWarhead** [comment]
Talvez eu esteja errado, mas X,Y não deveriam ser um único elemento da lista? Acho que do jeito que está escrito é como se fossem elementos diferentes.

**Comment by flavioduart** [comment]
Talvez se quando fizer a função para todos os ângulos, ela pegue. Também não consegui entender o porquê de ta [2,1] toda vez.

**Comment by drbeco** [comment]
`casaatual([X,Y])` está certa. Pode ser considerado um **par ordenado**, ou seja, é uma dupla de elementos, mas que pode ela mesma ser considerada **um único** elemento numa lista de pares ordenados (exemplo, casas visitadas: `[[1,1], [1,2], [1,3]]`. Se pegar um elemento dessa lista, é um par ordenado que representa as duas coordenadas **X, Y**).

Acho que casaemfrente não precisa ser um predicado dinâmico a ser memorizado (não precisa usar `assert`). Acho que basta calcular _a quente_ cada vez que precisar. Não é algo que precisa ser _lembrado_, pois pode ser _deduzido_ direto da posição/orientação.

Por isso o bug #15 sugere apenas um predicado simples, sem `assert/retractall`

**Comment by guilhermediasl** [comment]
Entendi professor , cada rodada a "frente" será atualizada baseando nos fatos dinâmicos de ângulo e da casa atual , mas para que a casa frente possa ser usada em outras funções ela não precisaria se tornar um fato?

**Comment by drbeco** [comment]
Não precisa ser **fato**, pode ser **regra**. Basta chamar a regra com as variáveis livres e a regra retornará com os valores corretos à frente.

**Comment by guilhermediasl** [comment]
Obrigado professor , solucionamos o problema.
