### ISSUE TITLE
Problema com a funcao casas adjacentes

### ISSUE THREAD

**Issue by guilhermediasl** [iWarhead/wumpusgrp3#27]
Nossa função casas adjacentes usa uma lista que recebe nela todas as casas perto da que o agente esta , adicionando 1 ou subtraindo da coluna ou linha (C,L). Para remover dessa lista as casas que não existem por estarem fora do mundo usamos varias regras parecidas com:
naozero:-
170     casaadj([[X1,Y],[X,Y2],[X3,Y],[X,Y4]]),
171     X1 < 1,
172     retractall(casaadj(_)),
173     assert(casaadj([[X,Y2],[X3,Y],[X,Y4]])).

Porem quando o agente esta nas "quinas" do mundo, essa regra só funciona para remover uma casa, acredito que seja por que depois de rodar pela primeira vez , o fato casaadj([[X,Y2],[X3,Y],[X,Y4]]) só tem 3 elementos , como poderíamos resolver isso?

**Comment by drbeco** [comment]
Dica: o melhor é nem adicionar errado para depois ter que remover. (Issue: coloque label e milestone)

**Comment by guilhermediasl** [comment]
Tentaremos fazer de outro jeito então , obrigado pela dica professor!

**Comment by guilhermediasl** [comment]
Problema resolvido.
