### ISSUE TITLE
Movimentação do agente

### ISSUE THREAD

**Issue by iWarhead** [iWarhead/wumpusgrp3#29]
Atualmente, o nosso agente está virando à direita sempre que sente algum perigo, porem isto pode fazer com o que o agente entre em um loop infinito de virar a direita, andar, virar a direita, andar, sempre voltando de uma casa a outra.
Sugestões?

**Comment by flavioduart** [comment]
Creio que tem que botar algo para depois que ele sentir o perigo, da retracall pra tirar a regra dele virar, e dar assert em outra regra, como o gofoward, assim ele não ficaria em um loop

**Comment by iWarhead** [comment]
Na verdade acho que o que precisa ser alterado é a regra do gofoward caso ele não sinta nada, pois com essa regra ele apenas irá se mover entre as casas da esquerda e de baixo. Para ir para a casa 2,2 por exemplo, precisaria ele virar para cima na [1,1], andar para frente, e virar a direita mesmo sem sentir perigo, depois andar para frente. Deu pra entender?

**Comment by flavioduart** [comment]
Entendi mais ou menos. Tenta, faz um teste com tua ideia.

**Comment by iWarhead** [comment]
Acho melhor fazer a lista de casas seguras primeiro, e depois resolver isso. Vou começar ela aqui.
