### ISSUE TITLE
Casas seguras

### ISSUE THREAD

**Issue by guilhermediasl** [iWarhead/wumpusgrp3#31]
Nossa lista de casas seguras esta usando a função "append" para acrescentar à lista as adjacentes quando a percepção do agente é toda "no", porem dessa forma as casas são adicionadas mais de uma vez. Como poderíamos resolver isso?

**Comment by guilhermediasl** [comment]
Problema resolvido.

**Comment by drbeco** [comment]
Foi resolvido como ?

**Comment by guilhermediasl** [comment]
Usando list_to_set(CasasSeguras,CasasSeguras2) para remover as casas repetidas depois de serem adicionadas.

**Comment by drbeco** [comment]
Perfeito.
