### ISSUE TITLE
Movimentação em função da lista de casas seguras

### ISSUE THREAD

**Issue by guilhermediasl** [iWarhead/wumpusgrp3#32]
Ja estamos com as funções de casas adjacentes , seguras , visitadas , e possiveis buracos prontas. Mas não estamos conseguindo por a movimentação do agente em função disso. 
Atualmente o agente anda ate sentir brisa e volta.
 Como poderiamos criar o algoritmo que dependa das listas de casas? Por exemplo, o agente esta na (2,1) e precisa ir pra (3,3).

**Comment by eilins** [comment]
Acho que utilizando as informações do tipo das casas que ainda não foram visitadas, e das não seguras. Porque tendo a lista das possíveis casas não seguras e tendo as não visitadas, fica mais fácil do agente deduzir que as demais casas não há perigo e fazer ele andar pelo mapa. Não sei se o raciocínio ta certo, mas acho que é basicamente isso, só que para tal, a gente ainda precisa fazer ele se movimentar pelo meio do mapa.

**Comment by guilhermediasl** [comment]
A lista de casas que ele teria que ir seriam as não seguras menos visitadas,essa lista é muito simples de se fazer , porém o problema é fazer o agente ir até tal casa

**Comment by drbeco** [comment]
"não seguras menos visitadas"? Não entendi.

**Comment by guilhermediasl** [comment]
As (Lista de Casas Seguras)-(Lista Casas Visitadas).
Me expressei  errado. Isso daria a Lista de casas que ele teria que ir.

**Comment by drbeco** [comment]
"_porém o problema é fazer o agente ir até tal casa_"

Esta é a grande sacada do jogo

**Comment by flavioduart** [comment]
Talvez criando uma função que chame a posição, e que verifica se essa posição faz parte das listas seguras, então se fizer, ele anda. Talvez essa seja a ideia

**Comment by iWarhead** [comment]
Mas é importante fazer ele andar prioritariamente pelas casas não visitadas, pra evitar que ele fique dando voltas desnecessárias.
