### ISSUE TITLE
Simulador V.3

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#4]
Cientes que mudou a versão do simulador?

Agora só sorteia 3 buracos!

Use:

`wumpusworld(pit3, 4).`

**Comment by flavioduart** [comment]
Estamos todos cientes. Mudaremos assim que possível e continuaremos o trabalho.

**Comment by flavioduart** [comment]
Pronto professor, agente atualizado.
Boa noite.

**Comment by drbeco** [comment]
** ATENÇÃO **

Nova atualização. Coloquei uma definição de módulo, para proteger o simulador de acesso indevido do agente.

A única função externa do simulador é a função `start`, para começar o jogo.

O resto é interna e não deve ser usada. Qualquer dedução sobre o mundo o agente deve fazer por si só, por seus próprios meios (e não consultar o simulador).

Atualizem os seus ramos master e develop (`git pull`).

---
Após lerem aqui, o último fechar o bug.

**Comment by flavioduart** [comment]
Entendido professor, faremos isso.

**Comment by iWarhead** [comment]
Entendido professor.Eu li a mensagem no servidor mas suas mensagens estão desativadas caso o senhor esteja esperando alguma resposta por lá.Meu grupo é o grupo 3
Att,Arthur Felipe de Olivera Bezerra

Date: Tue, 24 Nov 2015 15:02:38 -0800

**Comment by drbeco** [comment]
Ok! Obrigado por me avisar.

**Comment by iWarhead** [comment]
Desculpa responder pelo email, raciocínio.exe parou de funcionar rsrs

**Comment by guilhermediasl** [comment]
Entendido professor

**Comment by eilins** [comment]
Entendido.

**Comment by eilins** [comment]
Entendido.
