### ISSUE TITLE
Sem issues?

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#6]
Como assim? Não tem nenhuma discussão? Ou o código não existe ou está perfeito.

Acredito que não é nenhum dos dois casos.

Parem de conversar pelo whatsapp e comecem a REGISTRAR a atividade. Eu não corrijo o whatsapp. .

**Comment by flavioduart** [comment]
Realmente. Pedimos desculpa professor, estamos criando mais issues e trabalhando mais online, e deixando o Whatsapp.
