### ISSUE TITLE
Conferir milestones

### ISSUE THREAD

**Issue by drbeco** [iWarhead/wumpusgrp3#7]
N | Data | Milestone | Descrição
----|----|----|----
1 | 17/11/15 | Versão 0.1 | Criar repositório, rascunhos, clones, ramos, add autores
2 | 19/11/15 | Versão 0.2 | Fazer um agente funcional mínimo que passeie pelo labirinto
3 | 26/11/15 | Versão 0.3 | Colocar alguma inteligência no agente
4 | 03/12/15 | Versão 0.4 | Melhorar as respostas dadas para as percepções do agente
5 | 10/12/15 | Versão 0.5 | Lembrar dos caminhos, casas seguras, pegar o ouro com sucesso
6 | 17/12/15 | Versão 1.0 | Buscar a saída através de caminho seguro. Versão Final
7 | 20/12/15 | Versão 1.1 | Versão final após adiamento.

**Comment by drbeco** [comment]
Nomes com as datas erradas, e faltando 3 milestones. Confira toda a tabela. Crie mesmo os atrasados. Os nomes são Versão XXX.

**Comment by flavioduart** [comment]
Pronto professor, todas as milestones editadas de acordo com a tabela, e a milestone que faltava criada.
