### ISSUE TITLE
Ação de retorno?

### ISSUE THREAD

**Issue by iWarhead** [iWarhead/wumpusgrp3#8]
Precisamos encontrar uma maneira de fazer o agente "retornar" para a casa anterior caso ele sinta uma brisa ou o fedor. Sugestões?

**Comment by guilhermediasl** [comment]
Acredito que seria usando retract com assert

**Comment by flavioduart** [comment]
Podemos testar a ideia de Guilherme, acredito que funcione.

**Comment by drbeco** [comment]
Concordo
