### ISSUE TITLE
Tirar o modo de repetição

### ISSUE THREAD

**Issue by flavioduart** [iWarhead/wumpusgrp3#9]
Pessoal, temos que ver o seguinte: quando ele sente a brisa por causa do buraco, ele vira a direita, e nesse momento deveria fazer outro comando, mas ao invés disso fica virando a direita e em uma repetição constante, gerando um bug. Como podemos resolver?

**Comment by iWarhead** [comment]
Isso é por que mesmo virando a direita, ele continua sentindo a brisa, afinal ele não saiu da casa. Para resolver isso precisamos dar um jeito para que ele volte para a casa anterior ao sentir brisa/fedor, e então explorar outros caminhos alternativos.

**Comment by guilhermediasl** [comment]
Por esse motivo vamos precisar criar o conceito de casa segura , para criar as regras baseando-se nisso

**Comment by eilins** [comment]
Mas nesse caso, criando o conceito de casa segura, é apenas para ele ter a percepção de ao sentir brisa/fedor, certo? Porque se não acabaria criando uma rota fixa para ele , e a gente tem de lembrar que a cada nova partida os buracos mudam de posição aleatoriamente, mesmo sendo uma quantidade fixa.

**Comment by drbeco** [comment]
O agente precisa lembrar que já virou uma vez. Precisa de algum tipo de "memória", que é conseguida com `assert` e `retractall`. Pode ser criativo e fazer `assert` de qualquer coisa que faça sentido. 

- O simulador chama o agente e passa uma percepção
- O agente tem a percepção e manda a ação pro simulador. O agente `retorna`. A partir daqui o agente "desaparece", pois todos predicados que você escreveu retornam. Então na próxima rodada, o agente não vai "lembrar" o que já fez antes, a não ser que você faça alguma marca.

**Comment by flavioduart** [comment]
Usamos o assert e conseguimos resolver esse bug, obrigado pela ajuda professor.
